"""Add users and user_id in tags, tasks

Revision ID: 002d9ae3f7cc
Revises: 1bcd6edc6ae3
Create Date: 2026-08-21 09:15:09.355433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002d9ae3f7cc'
down_revision: Union[str, Sequence[str], None] = '1bcd6edc6ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("""
	INSERT INTO users (email, hashed_password, is_active, created_at)
	VALUES ('default@example.com', 'fake_hashed_password', true, NOW())
	ON CONFLICT (email) DO NOTHING
	RETURNING id
    """)

    op.execute("""
	UPDATE tags
	SET user_id = (SELECT id FROM users WHERE email = 'default@example.com')
	WHERE user_id IS NULL
    """)

    op.alter_column('tags', 'user_id', nullable=False)

    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("""
	UPDATE tasks
	SET user_id = (SELECT id FROM users WHERE email = 'default@example.com')
	WHERE user_id IS NULL
    """)

    op.alter_column('tasks', 'user_id', nullable=False) 

    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_column('tags', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
