"""Fourth revision

Revision ID: 1bcd6edc6ae3
Revises: 36b1569a9549
Create Date: 2026-08-14 12:10:47.978964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcd6edc6ae3'
down_revision: Union[str, Sequence[str], None] = '36b1569a9549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Tasks_tag_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('Tasks_tag_id_fkey'), 'tasks', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
