"""Third revision

Revision ID: 36b1569a9549
Revises: 892fdeeca6b2
Create Date: 2026-08-14 10:23:57.969743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b1569a9549'
down_revision: Union[str, Sequence[str], None] = '892fdeeca6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tags_id'), table_name='tags')
    op.drop_index(op.f('ix_Tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.add_column('tasks', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_Tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_Tasks_tag_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_tag_id'), 'tasks', ['tag_id'], unique=False)
    op.drop_column('tasks', 'state')
    op.drop_column('tasks', 'created_date')
    op.drop_column('tasks', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_tag_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index(op.f('ix_Tasks_tag_id'), 'tasks', ['tag_id'], unique=False)
    op.create_index(op.f('ix_Tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'description')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index(op.f('ix_Tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_Tags_id'), 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
