"""Initial revision

Revision ID: 5a3b72b15424
Revises: 
Create Date: 2026-08-13 16:50:30.989580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3b72b15424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tags_id'), 'Tags', ['id'], unique=False)
    op.create_index(op.f('ix_Tags_name'), 'Tags', ['name'], unique=True)
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['Tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tasks_id'), 'Tasks', ['id'], unique=False)
    op.create_index(op.f('ix_Tasks_tag_id'), 'Tasks', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_tag_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_id'), table_name='Tasks')
    op.drop_table('Tasks')
    op.drop_index(op.f('ix_Tags_name'), table_name='Tags')
    op.drop_index(op.f('ix_Tags_id'), table_name='Tags')
    op.drop_table('Tags')
    # ### end Alembic commands ###
