"""Second revision

Revision ID: 892fdeeca6b2
Revises: 5a3b72b15424
Create Date: 2026-08-13 16:55:48.448358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '892fdeeca6b2'
down_revision: Union[str, Sequence[str], None] = '5a3b72b15424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Tags', 'tags')
    op.rename_table('Tasks', 'tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Tags', 'tags')
    op.rename_table('Tasks', 'tasks')
    # ### end Alembic commands ###
